### ISSUE TITLE
Bug Report: User Stuck in New Scenario Window

### ISSUE THREAD

**Issue by persaud29** [connordear/eecs2311group2#2]
# User Stuck in New Scenario Window

## Summary

After creating a scenario and saving the file, there is no option to go back to the main menu to perform any other actions. The user must terminate the application and run it again.

## Technical Specification

Operating System: Windows 10
Java Version: 8
Component: 'New' to create a new scenario
Bug Report Author: Andrew Maywapersaud

## Severity

The severity of this bug is MAJOR. Being stuck in one screen hinders the users functional use of the application. It is inconvenient to exit and reload the application in order to perform operations with your new scenario. 

## Priority

Due to loss of functionality, the priority is marked as P1.

## Description

	
**Steps to Reproduce:**
To reproduce this bug, click on ‘new’. Enter a scenario title and applicable braille cell information. Then click on ‘create’. The user is now stuck in this window unless they terminate the application.
	
**Actual Results:**
The user can create a scenario using the actions that the group specified to be implemented. The scenario can be saved. However, you cannot perform any other action after this unless you terminate the application.

**Expected Results:**
The expected result is to be able to run the created scenario promptly after making it. Moreover, it is expected we can perform all the given functionalities without having to terminate in order to get to a specific part. 

## Screen Shots

The following figure illustrates the window the user gets stuck in:

![trete](https://user-images.githubusercontent.com/23734635/37069433-5f9a0808-2181-11e8-8eb3-493f1e23d96c.png)

**Comment by connordear** [comment]
Fixed by @hasibr in icon update
