### ISSUE TITLE
Saving and Opening File Feature Request 

### ISSUE THREAD

**Issue by rajvichavada** [connordear/eecs2311group2#3]
Author: Rajvi Chavada

## Summary:
A request to edit the save and open file feature in a scenario list panel to ease the accessibility for users.

## System Details
OS: Windows 10 (Home)
Java Version: SE 5.0
Released Version Used: vM
Severity: Minor (it is a feature recommendation)

## Description:
Once the file is saved, the user is unable to change the name or the location of the saved file. It is seen that there exists a drop-down menu where the user can save, save as, new, and open that is not functional right now but serves as a great feature. In addition, a feature where all the scenario files are listed in a separate panel within the editor panel or main menu would allow for more accessibility. The user would be able to visually see the list of files and also be able to click on existing files to open them up. 
 
## Steps to Reproduce
1.  Click "New" from main menu
2.  Enter the new scenario credentials
3. Exit program to open new scenario files

## Expected Results
A user might want to navigate back to the main menu, view the file they have created, or load files in their directory without exiting the application.

## Actual Results
The user has to exit the program to create another file or open new files. 

## Result Improvement with suggested feature
If a separate panel is located in the "Braille Author" window, the user can visually see the list of the created scenarios, and open scenarios while being on the same page. This feature allows for singularity as it avoids having several windows open up for various functions of the app and eases the accessibility.

**Comment by connordear** [comment]
Save as is now working in most recent push
